config/routes.rb
Rails.application.routes.draw do
  root to: 'flats#homepage'

  devise_for :users

  resources :flats do
    resources :bookings, only: [:new, :create]
    resources :comments, only: [:new, :create, :update]
  end
  resources :bookings, except: [:new, :create]
  resources :comments, except: [:new, :create, :update]

  # ----------------------------- ADDITONNAL ROUTES ----------------------------------#

  # FLATS CONTROLLER
  get "my_flats", to: "flats#my_flats"
  # BOOKINGS CONTROLLER
  get "my_bookings", to: "bookings#my_bookings"
  get "my_demands", to: "bookings#my_demands"
  get "show_demand", to: "bookings#show_demand"
  # BOOKINGS CONTROLLER
  get "contact", to: "pages#contact"
  get "infos", to: "pages#infos"

  # ----------------------------------------------- #
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat

  validates :arrival, :departure, presence: true
  # validates :departure, comparison: { greater_than: :arrival }
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    # Sur la SHOW de FLATS
  end

  def create
    set_flat
    @booking = Booking.new(booking_params)
    @booking.flat = @flat
    @booking.user = current_user
    if @booking.departure >= @booking.arrival
      if @booking.save
        redirect_to flat_path(@flat)
        flash[:notice] = "Réservation envoyée! Vous pouvez consulter vos demandes depuis votre profil."
        # redirect_to my_bookings_path
      else
        render "flats/show"
      end
    else
      render "flats/show"
      flash[:alert] = "Erreur au niveau des dates !"
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to my_bookings_path
  end

  def my_bookings
    @bookings = Booking.where(user_id: current_user).order(created_at: :desc)
  end

  def my_demands
    @bookings = Booking.joins(:flat).where(flats: { user_id: current_user }).order(created_at: :desc)
  end

  # UPDATE is for proprio == Accept or No
  def update
    @booking = Booking.find(params[:id])
    if @booking.update(accepted_params)
      redirect_to my_demands_path
    else
      render :my_demands
    end
  end

  private

  def set_flat
    @flat = Flat.find(params[:flat_id])
  end

  def booking_params
    params.require(:booking).permit(:arrival, :departure, :flat_id, :user_id)
  end

  def accepted_params
    params.require(:booking).permit(:accepted)
  end
end

app/views/bookings/my_bookings.html.erb
<div class="container">
  <% if @bookings.empty? %>
    <section class="blank_page">
      <h2>Aucun résultat</h2>
    </section>
  <% else %>
    <section class="my-bookings">
      <h2>Mes Réservations</h2>
      <div class="grid-bookings">
        <% @bookings.each do |bkg| %>
          <div class="card-books">
            <h2><%= bkg.flat.name %></h2>
            <p>Début : <%= bkg.arrival.strftime('%d/%m/%Y') %></p>
            <p>Fin : <%= bkg.departure.strftime('%d/%m/%Y') %></p>
            <p>Durée : <%= @days = (bkg.arrival..bkg.departure).count %> jours</p>
            <p>Prix journalier : <%= @price = bkg.flat.daily_price %>€</p>
            <p>Montant TOTAL : <%= @days * @price %>€</p>
            <% if bkg.accepted %>
              <p class="status-yes">Statut : Acceptéé</p>
            <% else %>
              <p class="status-wait">Statut : En attente</p>
              <br>
              <%= link_to "Annuler la réservation", booking_path(bkg), method: :delete, data: { confirm: "Etes vous sure?" }, class: "btn-cancel-booking" %>
            <% end %>
          </div>
        <% end %>
      </div>
    </section>
  <% end %>
</div>

<%# Date format "Lundi 13 Septembre 2022" mais en anglais %>
<% Date.parse(DateTime.now.to_s).strftime('%A %d %B %Y') %>

app/views/bookings/my_demands.html.erb
<div class="container">
  <% if @bookings.empty? %>
    <div class="blank_page">
      <h2>Aucun résultat</h2>
    </div>
  <% else %>
    <section class="my-demands">
      <h2>Demande de réservation pour :</h2>
      <div class="grid-bookings">
        <% @bookings.each do |bkg| %>
            <div class="card-books">
              <h2><%= link_to bkg.flat.name, flat_path(bkg.flat) %></h2>
              <p>Début : <%= bkg.arrival.strftime('%d/%m/%Y') %></p>
              <p>Fin : <%= bkg.departure .strftime('%d/%m/%Y')%></p>
              <p>Durée : <%= @days = (bkg.arrival..bkg.departure).count %> nuits</p>
              <% @price = bkg.flat.daily_price %>
              <p>Montant : <%= @days * @price %>€</p>
              <% if bkg.accepted %>
                <h4>Réservation acceptée</h4>
              <% elsif bkg.accepted == false %>
                <%= link_to "Supprimer", (bkg), method: :delete, data: { confirm: "Etes vous sure?" }, class: "btn btn-danger" %>
              <% else %>
                <%= simple_form_for([@flat, bkg], :method => :patch) do |f| %>
                  <div class="valid-booking">
                    <%= f.collection_radio_buttons :accepted, [[false, 'Refuser'], [true, 'Accepter']], :first, :last %>
                  </div>
                  <%= f.submit "Valider", class: "btn btn-primary" %>
                <% end %>
              <% end %>
            </div>
        <% end %>
      </div>
    </section>
  <% end %>
</div>