config/routes.rb
Rails.application.routes.draw do
  root to: 'flats#homepage'

  devise_for :users

  resources :flats do
    resources :bookings, only: [:new, :create]
    resources :comments, only: [:new, :create, :update]
  end
  resources :bookings, except: [:new, :create]
  resources :comments, except: [:new, :create, :update]

  # ----------------------------- ADDITONNAL ROUTES ----------------------------------#

  # FLATS CONTROLLER
  get "my_flats", to: "flats#my_flats"
  # BOOKINGS CONTROLLER
  get "my_bookings", to: "bookings#my_bookings"
  get "my_demands", to: "bookings#my_demands"
  get "show_demand", to: "bookings#show_demand"
  # BOOKINGS CONTROLLER
  get "contact", to: "pages#contact"
  get "infos", to: "pages#infos"

  # ----------------------------------------------- #
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer-save.html.erb
<footer>
  <section class="dropup">
    <button class="dropbtn">Réseaux</button>
    <div class="dropup-content">
      <%= link_to "","https://www.linkedin.com/in/ludovic-nourel/", class: "fab fa-linkedin", target: :_blank, rel: 'noopener' %>
      <%= link_to "","https://github.com/Ludo97212", class: "fab fa-github", target: :_blank, rel: 'noopener' %>
      <%= link_to "","#", class: "fab fa-instagram" %>
      <%= link_to "","#", class: "fab fa-facebook" %>
      <%= link_to "","#", class: "fab fa-twitter" %>
    </div>
  </section>

  <section class="footer-section">
    <%= link_to "Mentions Légales","/infos", class: "cpr"%>
  </section>

  <section class="footer-section">
    <%= link_to "","https://www.linkedin.com/in/ludovic-nourel/", class: "fab fa-linkedin", target: :_blank, rel: 'noopener' %>
      <%= link_to "","https://github.com/Ludo97212", class: "fab fa-github", target: :_blank, rel: 'noopener' %>
      <%= link_to "","#", class: "fab fa-instagram" %>
      <%= link_to "","#", class: "fab fa-facebook" %>
      <%= link_to "","#", class: "fab fa-twitter" %>
  </section>

  <section class="footer-section">
    <%= link_to "Contact", "/contacts", class: "cpr" %>
  </section>
</footer>

app/views/shared/_footer.html.erb
<footer>
  <section class="footer-section">
    <h4 class="footer-header">Informations</h4>
    <p>@RentAFlat 2023</p>
    <%= link_to "Mentions Légales","/infos" %>
    <%= link_to "CGV","/infos" %>
    <%= link_to "Politique de confidentialité","/infos" %>
  </section>

  <section class="footer-section">
    <h4 class="footer-header">Réseaux</h4>
    <section class="footer-icons">
      <%= link_to "","#", class: "fab fa-youtube" %>
      <%= link_to "","https://www.linkedin.com/in/ludovic-nourel/", class: "fab fa-linkedin", target: :_blank, rel: 'noopener' %>
      <%= link_to "","#", class: "fab fa-instagram" %>
      <%= link_to "","#", class: "fab fa-facebook" %>
      <%= link_to "","#", class: "fab fa-twitter" %>
    </section>
  </section>

  <section class="footer-section">
    <h4 class="footer-header">Renseignements</h4>
    <%= link_to "Contact", "/contact" %>
    <p>Bat 875, Rue des Affaires Etrangères, <br>75001, Paris, France</p>
    <%= link_to "Plan du site","/infos" %>
    <p></p>
  </section>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div>
  <%= link_to root_path do %>
    <i class="fa-solid fa-house-chimney-user"></i>
    <% end %>
  </div>
  <div>
    <h1>Rent'Flat</h1>
  </div>
  <div class="user_options">
    <div>
      <% if current_user != nil %>
        <p><%= current_user.email %></p>
      <% else %>
        <%= link_to "S'inscrire !", new_user_registration_path %>
      <% end %>
    </div>

    <div class="nav-user">
      <ul>
        <li><%= image_tag "avatar1-yellow.png", class: "avatar dropdown-toggle" %>
          <ul class="dropdown">
            <% if current_user != nil %>
            <p>. <%= link_to "Mes Apparts' à louer", my_flats_path %></p>
            <p>. <%= link_to "Mes Reservations", my_bookings_path %></p>
            <p>. <%= link_to "Mes Demandes", my_demands_path %></p>
            <p>. <%= link_to "Modifier profil", edit_user_registration_path %></p>
            <p>. <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></p>
            <% else %>
               <%= link_to "Connexion", new_user_session_path %>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar2.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <section>
      <%= link_to "/", class: "navbar-brand" do %>
        <i class="fa-solid fa-house-chimney-user"></i>
      <% end %>
    </section>
    <section>
      <a class="navbar-header" href="/">Rent A Flat</a></a>
    </section>

    <section>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li>
            <% if user_signed_in? %>
              <%= current_user.email %>
            <% else %>
              <%= link_to "S'inscrire !", new_user_registration_path %>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "avatar1-yellow.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if user_signed_in? %>
                <%= link_to "Mes Apparts' à louer", my_flats_path, class: "dropdown-item" %>
                <%= link_to "Ajouter une offre", new_flat_path, class: "dropdown-item" %>
                <%= link_to "Mes Reservations", my_bookings_path, class: "dropdown-item" %>
                <%= link_to "Mes Demandes", my_demands_path, class: "dropdown-item" %>
                <%= link_to "Modifier profil", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Se déconnecter", destroy_user_session_path, class: "dropdown-item", method: :delete %>
              <% else %>
                <%= link_to "Connexion", new_user_session_path, class: "dropdown-item" %>
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    </section>
  </div>
</div>